### ISSUE TITLE
Navigation for about page

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#25]
@stanblum see the dropdown navigation for the about page at https://tdwg.github.io/website-jekyll/

Any suggestions on how to organize these pages (differently)?

```yml
- text: About
  menu:
  - text: About
    href: /about/
  - text: "---"
  - text: Executive committee
    href: true
  - text: Functional subcommittees # Could also directly list them here
    href: true
  - text: Process
    href: true
  - text: Constitution
    href: true
  - text: Incorporation and status
    href: true
  - text: "---"
  - text: Membership
    href: true  
  - text: Terms of use
    href: true
  - text: Code of conduct
    href: true
  - text: Diversity and inclusion statement
    href: true
  - text: Liability disclaimer and release
    href: true
  - text: Review manager guidelines
    href: true
  - text: Contributing to the website
    href: true
  - text: "---"
  - text: Logos
    href: true
  - text: Contact
    href: true
```
